
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'exprDIVISAO DIVISAO_INTEIRA FLOAT INT MAIS MENOS MULTIPLICACAO PARENTESE_ABRE PARENTESE_FECHA PRINT STRINGexpr : PRINT PARENTESE_ABRE expr PARENTESE_FECHAexpr : expr MAIS termoexpr : expr MENOS termoexpr : expr DIVISAO termoexpr : expr MULTIPLICACAO termoexpr : expr DIVISAO_INTEIRA termoexpr : termotermo : fatorfator : INT\n| FLOATtermo : FLOATtermo : INTtermo : STRINGtermo : PARENTESE_ABRE expr PARENTESE_FECHA'
    
_lr_action_items = {'PRINT':([0,3,14,],[2,2,2,]),'FLOAT':([0,3,9,10,11,12,13,14,],[6,6,6,6,6,6,6,6,]),'INT':([0,3,9,10,11,12,13,14,],[7,7,7,7,7,7,7,7,]),'STRING':([0,3,9,10,11,12,13,14,],[8,8,8,8,8,8,8,8,]),'PARENTESE_ABRE':([0,2,3,9,10,11,12,13,14,],[3,14,3,3,3,3,3,3,3,]),'$end':([1,4,5,6,7,8,16,17,18,19,20,22,23,],[0,-7,-8,-10,-9,-13,-2,-3,-4,-5,-6,-14,-1,]),'MAIS':([1,4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[9,-7,-8,-10,-9,-13,9,-2,-3,-4,-5,-6,9,-14,-1,]),'MENOS':([1,4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[10,-7,-8,-10,-9,-13,10,-2,-3,-4,-5,-6,10,-14,-1,]),'DIVISAO':([1,4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[11,-7,-8,-10,-9,-13,11,-2,-3,-4,-5,-6,11,-14,-1,]),'MULTIPLICACAO':([1,4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[12,-7,-8,-10,-9,-13,12,-2,-3,-4,-5,-6,12,-14,-1,]),'DIVISAO_INTEIRA':([1,4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[13,-7,-8,-10,-9,-13,13,-2,-3,-4,-5,-6,13,-14,-1,]),'PARENTESE_FECHA':([4,5,6,7,8,15,16,17,18,19,20,21,22,23,],[-7,-8,-10,-9,-13,22,-2,-3,-4,-5,-6,23,-14,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,14,],[1,15,21,]),'termo':([0,3,9,10,11,12,13,14,],[4,4,16,17,18,19,20,4,]),'fator':([0,3,9,10,11,12,13,14,],[5,5,5,5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> PRINT PARENTESE_ABRE expr PARENTESE_FECHA','expr',4,'p_expr_print','parser-ref.py',54),
  ('expr -> expr MAIS termo','expr',3,'p_expr_mais','parser-ref.py',61),
  ('expr -> expr MENOS termo','expr',3,'p_expr_menos','parser-ref.py',68),
  ('expr -> expr DIVISAO termo','expr',3,'p_expr_divisao','parser-ref.py',75),
  ('expr -> expr MULTIPLICACAO termo','expr',3,'p_expr_multiplicacao','parser-ref.py',82),
  ('expr -> expr DIVISAO_INTEIRA termo','expr',3,'p_expr_divisao_inteira','parser-ref.py',89),
  ('expr -> termo','expr',1,'p_expr_termo','parser-ref.py',98),
  ('termo -> fator','termo',1,'p_termo_fator','parser-ref.py',103),
  ('fator -> INT','fator',1,'p_fator_num','parser-ref.py',108),
  ('fator -> FLOAT','fator',1,'p_fator_num','parser-ref.py',109),
  ('termo -> FLOAT','termo',1,'p_termo_float','parser-ref.py',117),
  ('termo -> INT','termo',1,'p_termo_int','parser-ref.py',122),
  ('termo -> STRING','termo',1,'p_termo_string','parser-ref.py',127),
  ('termo -> PARENTESE_ABRE expr PARENTESE_FECHA','termo',3,'p_termo_parentese','parser-ref.py',132),
]
